"""Initial migration

Revision ID: 39a17921afa0
Revises: 
Create Date: 2025-06-19 22:58:39.876904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a17921afa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_addresses',
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_addresses_label'), 'service_addresses', ['label'], unique=True)
    op.create_table('service_blocks',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_blocks_hash'), 'service_blocks', ['hash'], unique=True)
    op.create_index(op.f('ix_service_blocks_height'), 'service_blocks', ['height'], unique=False)
    op.create_table('service_tokens',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('supply', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('reissuable', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tokens_ticker'), 'service_tokens', ['ticker'], unique=True)
    op.create_index(op.f('ix_service_tokens_type'), 'service_tokens', ['type'], unique=False)
    op.create_table('service_balances',
    sa.Column('received', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('locked', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('sent', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('token_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['service_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['service_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_balances_address_id'), 'service_balances', ['address_id'], unique=False)
    op.create_index(op.f('ix_service_balances_token_id'), 'service_balances', ['token_id'], unique=False)
    op.create_table('service_bans',
    sa.Column('txid', sa.String(length=64), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('block_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['service_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['admin_id'], ['service_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['block_id'], ['service_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_bans_address_id'), 'service_bans', ['address_id'], unique=False)
    op.create_index(op.f('ix_service_bans_admin_id'), 'service_bans', ['admin_id'], unique=False)
    op.create_index(op.f('ix_service_bans_block_id'), 'service_bans', ['block_id'], unique=False)
    op.create_index(op.f('ix_service_bans_txid'), 'service_bans', ['txid'], unique=True)
    op.create_table('service_costs',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('block_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['service_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['block_id'], ['service_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_costs_action'), 'service_costs', ['action'], unique=False)
    op.create_index(op.f('ix_service_costs_admin_id'), 'service_costs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_service_costs_block_id'), 'service_costs', ['block_id'], unique=False)
    op.create_index(op.f('ix_service_costs_height'), 'service_costs', ['height'], unique=False)
    op.create_index(op.f('ix_service_costs_type'), 'service_costs', ['type'], unique=False)
    op.create_table('service_fee_addresses',
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('block_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['service_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['block_id'], ['service_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_fee_addresses_admin_id'), 'service_fee_addresses', ['admin_id'], unique=False)
    op.create_index(op.f('ix_service_fee_addresses_block_id'), 'service_fee_addresses', ['block_id'], unique=False)
    op.create_index(op.f('ix_service_fee_addresses_height'), 'service_fee_addresses', ['height'], unique=False)
    op.create_index(op.f('ix_service_fee_addresses_label'), 'service_fee_addresses', ['label'], unique=True)
    op.create_table('service_transfers',
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('txid', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('has_lock', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=True),
    sa.Column('token_id', sa.Uuid(), nullable=True),
    sa.Column('receiver_id', sa.Uuid(), nullable=True),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['service_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['service_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['service_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['service_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_transfers_block_id'), 'service_transfers', ['block_id'], unique=False)
    op.create_index(op.f('ix_service_transfers_category'), 'service_transfers', ['category'], unique=False)
    op.create_index(op.f('ix_service_transfers_receiver_id'), 'service_transfers', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_service_transfers_sender_id'), 'service_transfers', ['sender_id'], unique=False)
    op.create_index(op.f('ix_service_transfers_token_id'), 'service_transfers', ['token_id'], unique=False)
    op.create_index(op.f('ix_service_transfers_txid'), 'service_transfers', ['txid'], unique=False)
    op.create_table('service_unbans',
    sa.Column('txid', sa.String(length=64), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('block_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['service_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['admin_id'], ['service_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['block_id'], ['service_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_unbans_address_id'), 'service_unbans', ['address_id'], unique=False)
    op.create_index(op.f('ix_service_unbans_admin_id'), 'service_unbans', ['admin_id'], unique=False)
    op.create_index(op.f('ix_service_unbans_block_id'), 'service_unbans', ['block_id'], unique=False)
    op.create_index(op.f('ix_service_unbans_txid'), 'service_unbans', ['txid'], unique=True)
    op.create_table('service_index',
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('transfer_id', sa.Uuid(), nullable=True),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('token_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['service_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['service_tokens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['service_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_index_address_id'), 'service_index', ['address_id'], unique=False)
    op.create_index(op.f('ix_service_index_category'), 'service_index', ['category'], unique=False)
    op.create_index(op.f('ix_service_index_token_id'), 'service_index', ['token_id'], unique=False)
    op.create_index(op.f('ix_service_index_transfer_id'), 'service_index', ['transfer_id'], unique=False)
    op.create_table('service_locks',
    sa.Column('value', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('unlock_height', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_id', sa.Uuid(), nullable=True),
    sa.Column('token_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['service_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['service_tokens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['service_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_locks_address_id'), 'service_locks', ['address_id'], unique=False)
    op.create_index(op.f('ix_service_locks_token_id'), 'service_locks', ['token_id'], unique=False)
    op.create_index(op.f('ix_service_locks_transfer_id'), 'service_locks', ['transfer_id'], unique=False)
    op.create_index(op.f('ix_service_locks_unlock_height'), 'service_locks', ['unlock_height'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_locks_unlock_height'), table_name='service_locks')
    op.drop_index(op.f('ix_service_locks_transfer_id'), table_name='service_locks')
    op.drop_index(op.f('ix_service_locks_token_id'), table_name='service_locks')
    op.drop_index(op.f('ix_service_locks_address_id'), table_name='service_locks')
    op.drop_table('service_locks')
    op.drop_index(op.f('ix_service_index_transfer_id'), table_name='service_index')
    op.drop_index(op.f('ix_service_index_token_id'), table_name='service_index')
    op.drop_index(op.f('ix_service_index_category'), table_name='service_index')
    op.drop_index(op.f('ix_service_index_address_id'), table_name='service_index')
    op.drop_table('service_index')
    op.drop_index(op.f('ix_service_unbans_txid'), table_name='service_unbans')
    op.drop_index(op.f('ix_service_unbans_block_id'), table_name='service_unbans')
    op.drop_index(op.f('ix_service_unbans_admin_id'), table_name='service_unbans')
    op.drop_index(op.f('ix_service_unbans_address_id'), table_name='service_unbans')
    op.drop_table('service_unbans')
    op.drop_index(op.f('ix_service_transfers_txid'), table_name='service_transfers')
    op.drop_index(op.f('ix_service_transfers_token_id'), table_name='service_transfers')
    op.drop_index(op.f('ix_service_transfers_sender_id'), table_name='service_transfers')
    op.drop_index(op.f('ix_service_transfers_receiver_id'), table_name='service_transfers')
    op.drop_index(op.f('ix_service_transfers_category'), table_name='service_transfers')
    op.drop_index(op.f('ix_service_transfers_block_id'), table_name='service_transfers')
    op.drop_table('service_transfers')
    op.drop_index(op.f('ix_service_fee_addresses_label'), table_name='service_fee_addresses')
    op.drop_index(op.f('ix_service_fee_addresses_height'), table_name='service_fee_addresses')
    op.drop_index(op.f('ix_service_fee_addresses_block_id'), table_name='service_fee_addresses')
    op.drop_index(op.f('ix_service_fee_addresses_admin_id'), table_name='service_fee_addresses')
    op.drop_table('service_fee_addresses')
    op.drop_index(op.f('ix_service_costs_type'), table_name='service_costs')
    op.drop_index(op.f('ix_service_costs_height'), table_name='service_costs')
    op.drop_index(op.f('ix_service_costs_block_id'), table_name='service_costs')
    op.drop_index(op.f('ix_service_costs_admin_id'), table_name='service_costs')
    op.drop_index(op.f('ix_service_costs_action'), table_name='service_costs')
    op.drop_table('service_costs')
    op.drop_index(op.f('ix_service_bans_txid'), table_name='service_bans')
    op.drop_index(op.f('ix_service_bans_block_id'), table_name='service_bans')
    op.drop_index(op.f('ix_service_bans_admin_id'), table_name='service_bans')
    op.drop_index(op.f('ix_service_bans_address_id'), table_name='service_bans')
    op.drop_table('service_bans')
    op.drop_index(op.f('ix_service_balances_token_id'), table_name='service_balances')
    op.drop_index(op.f('ix_service_balances_address_id'), table_name='service_balances')
    op.drop_table('service_balances')
    op.drop_index(op.f('ix_service_tokens_type'), table_name='service_tokens')
    op.drop_index(op.f('ix_service_tokens_ticker'), table_name='service_tokens')
    op.drop_table('service_tokens')
    op.drop_index(op.f('ix_service_blocks_height'), table_name='service_blocks')
    op.drop_index(op.f('ix_service_blocks_hash'), table_name='service_blocks')
    op.drop_table('service_blocks')
    op.drop_index(op.f('ix_service_addresses_label'), table_name='service_addresses')
    op.drop_table('service_addresses')
    # ### end Alembic commands ###
